### ISSUE TITLE
Add ability to run JS tests

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/drupal-container#1]
This has been implemented in Lando so it's a matter of getting it to work with docker compose.

**Comment by andybroomfield** [comment]
You'll need to install Chrome driver and selenium into the docker image I guess (I had to install these on my dev Mac to run them outside Lando).
Details are here https://www.drupal.org/node/2941464
Also need to alter the phpunit.xml.dist to include support for them.
