### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/drupal-container#31]
Add a `php8.2` branch to fix PHP 8.2 tests on https://github.com/localgovdrupal/localgov_microsites_project/pull/35 and https://github.com/localgovdrupal/localgov_project/pull/130 which pull the [localgovdrupal/apache-php image](https://github.com/localgovdrupal/drupal-container/)

**Comment by millnut** [comment]
@finnlewis @stephen-cox once I've pushed the branch for `php8.2` can either of you create the docker image please

Branch is here: https://github.com/localgovdrupal/drupal-container/tree/php8.2

**Comment by finnlewis** [comment]
I'll take a look, see if I can remind myself how to do it!

**Comment by finnlewis** [comment]
OK I think I've done it: https://hub.docker.com/layers/localgovdrupal/apache-php/php8.2/images/sha256-1d7850a341257c00b9a8865defded7895b7acde83fe81a21cc2fd81ea005f0d9?context=explore

Want to try it @millnut ?

**Comment by millnut** [comment]
@finnlewis worked great. Failures in the action are what I was expecting which are areas of the project which need some PHP 8.2 fixes, this can be closed now and I'll run 8.2 checks on both project and microsites_project to see what PHP 8.2 work needs looking at

**Comment by finnlewis** [comment]
Thanks @millnut ! 😺
