### ISSUE TITLE
PHP 8.3 for Drupal 10.2

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/drupal-container#32]
Created this just as a reminder to not forget to create a PHP 8.3 image ready for the Drupal 10.2 beta

**Comment by millnut** [comment]
@finnlewis @stephen-cox updated the PHP 8.3 image from rc to stable here https://github.com/localgovdrupal/drupal-container/tree/php8.3 can a new docker image be created please

**Comment by stephen-cox** [comment]
Hi @millnut, there's now a PHP 8.3 image for running tests: https://hub.docker.com/r/localgovdrupal/apache-php/tags

**Comment by stephen-cox** [comment]
This link works better https://hub.docker.com/r/localgovdrupal/apache-php/tags

**Comment by millnut** [comment]
> Hi @millnut, there's now a PHP 8.3 image for running tests: https://hub.docker.com/r/localgovdrupal/apache-php/tags

Great thank you @stephen-cox
